language: python
python:
- '3.5'
- '3.7'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: mosorio
  password:
    secure: LAMUdrzrZiOv/yWcStwQiWW4jqrvdSzvknIrXk0eqHXrT+mm7FG+c/wAIYANWmet9tbT46+fMiMS7cOXT8RVPE9pZmBvB92wTBhSAfw3+h1MxbMP8+RmOtXAKnT/CuB1clStvdoVBRGWFzgyHuKEac0mi7zSJaBfQ9rir3LDHTyTa++udlb72xjA98PDSCIrqlevIb9cChqNoyBV7sV6SqHN9Vx+/CE7OiEmxKqLCg5iJ5HPNd1Xrrvflkj8mOFXG1JaqFVoAoet4rIuGLYuiojEct+CfEEw2y8sse1F5Wqg5b089Go6gmQm2ToU1diMJh1O38yary147QysWM4KwJN1rhNXaHiM5VXOZ7V4k2Y3H0Hkk6CRgxtm8rgG1sigWVr/HOWfqlpetl84Wt+N+tnpygl0a4R/e6ayYIf/PUwW1l4VCLLOax2hd0Dj4La3kyTgX2etHPJzOU3EIDqvVYuiISaUyL8qq13Q94UMlT9UsPgCLOsR4+hIJvoLZ/BlHA7gQ9OwvQ6A+cCQ/JhJKZK+HRnE4mTQonZm+HFtMTukD+2mC5TgP9TpF5sxJ0oMiAyU60LVkFyTc/aE+IkerShDhsNngyizn0UhoR//TbCO/I0fEmTbb6r0u1W/UIKTGOu+1W+QdrfpJaf5X+QM5DZTPq5FoScdqgCrqMu/ncU=
  on:
    tags: true
  skip_existing: true
