language: python
python:
- '3.5'
- '3.7'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: WVKxZ08p49TCEP69cfQyRM5rWtRM4K8qxvdJTQOD3UmteKNOeYEiiE7oaZD+9EDIvH1y6tsc0YihZmwFFTMPS0T2zfRUglHtWUNc8jQi5dysd6MZZAG72cHIkCO8/FO5vIW6QaZ/mTf7Vj+frM9e1lHk5rGbpcMAldJkx7n0kfc/9LWLYbSbgWELY57LR6VUgI7gXEPXRVNGIxGkex6klIj952RTGEKpSmA2tNcehidhGnOOTUTrwmvhnCHWqMfXeU7L1f3rGsyYdEjNiiSKWUFZ7SyU4I9RBzu1yJfNkSppb1dK4+wifIVNBxkQLWQLELczGnr6nRkjnB0Kti1z8lf8+6zPwmccql4/cOatFCyKg5gYcFhoKXEfkWONGetIt/D5lInklApesE4dFvJt6bn/cNymEcIhNXwcaHMsgBtdeZyArHOAi4p8eDtV+mix/EnVedJTab2FF92wgSkCW9vhr4MmJNQCCL3KCnK07RT93nXMZ+6EC1P+JvowLuWHODmdEM9q5qDfAQObSXGjKGwH2Q0qQhMQzU6+EtlXaoSusZ2CXK8N51H+YtILbQ/k6XF3HY2VbuJU97Fx/shzvk5E2DWGerrxa8uvYtTooZnESbHnxrs6G+h1cnjmqfak/ykQqls0pIzLTeBm6ZkhbWDwT3cpGg5rLlXKM8CVuMQ=
  on:
    tags: true
  skip_existing: true
