site_name: Model Catalog Python client
nav:
  - Home: index.md
  - Searching models: models.md
  - Searching model configurations: modelconfigurations.md
  - Documentation for API Endpoints: endpoints/index.md 
theme: 
  name: material
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true